package com.healthcareunit;

import java.util.ArrayList;
import java.util.List;

import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;
import android.widget.Toast;

import data.AilementData;




public class Ailements extends Activity{	
	
	private List<AilementData> ailementdata;
	private int AmAtpage=-1;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.ailements);
		ProgressDialog dialog = new ProgressDialog(this);
		dialog.setMessage("Please wait...");
		dialog.show();	
		
		
		ailementdata= new ArrayList<AilementData>();
		
		ailementdata.add(new AilementData("AILMENTS\nDIABETES INFORMATION AND MANAGEMENT", "It’s often referred as diabetes mellitus, a group of metabolic disease in which a person has high blood glucose (blood sugar) either because insulin production is inadequate or because the body’s cells do not respond properly to insulin or both."));
		ailementdata.add(new AilementData("There are three types of diabetes as\nType 1 diabetes–", "The body doesn’t produce insulin (Approx 10% of diabetes patients are type 1) Type 1 patients should follow a healthy eating plan, do adequate exercise and take insulin injections the rest of their lives. Type 1 diabetes can lead normal life. People usually develop type 1 diabetes before their 40th year, often in early adulthood or teenage years."));
		ailementdata.add(new AilementData("Type 2 diabetes–", "The body doesn’t produce enough insulin for proper function (Approx 90% of diabetic patients are type 2) Type 2 diabetes is able to lead a health life by following a healthy diet, doing plenty of exercise and monitoring their blood sugar levels. They may also need to take oral medication and/or insulin to control blood glucose levels. Risks for cardio vascular disease if much higher for a diabetic, so it’s important blood pressure and cholesterol levels are monitored regularly."));
		ailementdata.add(new AilementData("Gestational diabetes", "This type affects female during pregnancy. Undiagnosed or uncontrolled gestational diabetes can raise the risk of complications during childbirth. The baby may be bigger than he/she should be. Women with a diet high in animal fat and cholesterol had a higher risk for gestational diabetes before becoming pregnant. This diabetes can be controlled by healthy diet and exercise. However all the diabetes types are treatable."));
		ailementdata.add(new AilementData("Tests for determining if a patient has diabetes are as follows:-", "-Fasting plasma glucose test\n		- Oral glucose tolerance test (OGTT)\n		- Hemoglobin A1C test\n		- Dilated eye exam\n		- Foot exam"));
		ailementdata.add(new AilementData("Complications related to uncontrolled diabetes", "Hypertension, heart problems, skin complications, foot complication, eye complications, mental health, hearing loss, gum disease, ketoacidosis, neuropathy, nephropathy, peripheral arterial disease, stroke, erectile dysfunction, healing of wounds"));
		ailementdata.add(new AilementData("Symptoms of diabetes", "-Frequent urination\n		- Intense thirst and hunger,\n		- Weight gain,\n		- Unusual weight loss,\n		- Fatigue,\n		- Cuts and bruises that do not heal,\n		- Male sexual dysfunction,\n		- Numbness,\n		- Tingling in hands and feet\nType 2 diabetes may need injection per day without any diabetes pills. Others may need a simple injection of insulin in the evening (at supper or bedtime along with pills) \nDiabetes dietary table\n		If you have diabetes or pre-diabetes your doctor will likely recommend you to see a dietician to guide you on dietary changes that will help you control your blood sugar (glucose) level and manage your weight. These can be based in regard to your health goals, tastes and lifestyle so that you can manage your eating habits 		"));		
		
		ailementdata.add(new AilementData("Recommended foods are:- ", "•Healthy carbohydrates i.e. fruits, vegetables, whole grains, legumes (beans, peas) and low fat dairy products\n		•Fiber rich foods i.e. include plant foods as whole wheat, vegetables, fruits, nuts, legumes, wheat bran\n		Heart – healthy fish i.e. eat atleast twice a week, salmon, tuna, mackerel are high in omega 3 fatty acids. •Good fats, avocados, almonds, walnuts, olives, peanut oils can help lower your cholesterol levels, eat them sparingly		"));
		ailementdata.add(new AilementData("Foods that are dangerous:- ", "•Saturated fats – hots dogs, beef, sausage and bacon\n		•Tran’s fats – found in processed food such as snacks, balced goods, shortening and stick margarines should be avoided.\n		•Cholesterol – sources include high fat dairy products, high fat animal proteins, egg yolks, shellfish, liver and other organ meats, aim for no more than 300 milligrams (mg) of cholesterol a day\n		•Sodium – aim for less than 2300mg of sodium a day\nInsulin injection depends on their blood glucose levels, those diagnosed with type 1 usually start with two injections per day of two different types of insulin and generally progress to three or four injections per day of different types. Regular insulin works best if you take it 30 minutes before you eat		"));
		ailementdata.add(new AilementData("CANCER INFORMATION AND MANAGEMENT", "Is a group of diseases that can cause any symptoms or signs. Cancer can grow places that it can cause symptoms or no symptoms at all. Having one symptom, may not be enough to figure out what is causing it. Medical tests such as x-rays, blood tests or biopsy may be needed to figure out. Its important to know the cause of symptoms, most people may ignore the symptoms, they don’t know those symptoms could mean something wrong, or they may be frightened by the symptoms results and don’t want medical help, or cannot afford medical care"));
		ailementdata.add(new AilementData("General symptoms/signs", "•Unexplained weight loss i.e. cancer of the pancreas, stomach, esophagus or lung\n		•Fever i.e. cancer of the lymphoma , leukemia\n		•Fatigue i.e. early in leukemia, colon or stomach cancer \n		•Pain i.e. early symptoms like bone cancer, testicular cancer, a headache that does not go away it might be a symptom of brain tumor, back pain can be a symptom of the colon, rectum or ovary cancer. Normally pain from cancer shows it has already spread from where it started, breast cancer.\n		•Skin changes i.e. darker looking skin, yellowish skin and eyes, reddened skin, itching, excessive hair growth\n		•Change in bowel habits or bladder function i.e. long term constipation, diarrhea, change in size of stool may be a sign of colon cancer, blood in urine or change in bladder function can be related to bladder or prostate cancer. Report immediately to your doctor any changes in bladder or bowel function to your medical practice\n		•Sores that do not heal I.e. Skin cancer, along lasting sour in the mouth could be oral cancer\n		•Unusual bleeding i.e. happens in early or advanced cases. Coughing blood (lung cancer), blood in stool (very dark or black like) stool can be colon or rectal cancer, abnormal vaginal bleeding (cancer or cervix endometrium). Blood in urine (bladder or kidney cancer) bloody discharge from nipple (breast cancer) report to your doctor immediately\n		•Thickening or lump in the breast or other parts of the body i.e. occurs breast, testides, lymph nodes (glands) and soft tissues of the body. Report to your doctor immediately.\n		•Indigestion or trouble swallowing i.e. swallowing and indigestion that don’t go away (cancer of esophagus, stomach or pharynx (throat). But most of the symptoms on this list are caused by something other than cancer. Contact your doctor immediately\n		•Change in a wart or any new skin change i.e. it might be skin cancer and other related factors. Please contact your doctor immediately\n		•Nagging cough/hoarseness related to cancer of larynx (voice box) or thyrot gland		"));
		ailementdata.add(new AilementData("Cancer tests", "Blood test \n•Complete blood count (CBC)\n		•Blood protein testing\n		•Tumor marker tests\n		•Circulating tumor cell tests\n		Other cancer tests are:-\n ?Mammography\n		?Pap test\n		?Biopsy\n		?Sigmoidoscopy\n		?Mitigated acquisition (MUGA) scan\n		?Positron emission tomography scan\n		?Magnetic resource imaging (MRI)\n		?Ultrasound scan\n		?Intergrated PET – CT scan\n		?Upper endoscopy		"));
		ailementdata.add(new AilementData("Cancer treatment", "?Chemotherapy\n		?Radiation therapy\n		?Targeted therapies\n		?Surgery\n		?Immunotherapy\n		?Blood donation and transfusion\n		?Photodynamic therapy (PDT)		"));
		ailementdata.add(new AilementData("Cancer treatment centres in Kenya:-", "?Aga Khan hospital Tel: 020366, 2037/2644, +254 (0) 732688911\n		?Beacon health service cancer centre Tel: 0714298000, +254 (0) 736998000\n		?Coast provincial general hospital Tel: +254 (0) 412314204, +254 722207868\n		?Kenyatta national hospital Tel: +254 202726450\n		?Kijiabe mission hospital Tel: +254 (0)203246500, +254 (0) 733779994\n		?Mater hospital Tel: +254 (0) 20651199, +254 (0) 733641870\n		?Moi teaching and referral hospital have clinics in Kitale, Webuye, Busia, Chulaimbo (Kisumu), Mosoroit, Turbo, Iten Tel: +254 721 176262, +254 704381628\n		?MP Shah hospital Tel: 0733606752, +254 203740132\n		?Nairobi Hospice Tel: 020271383\n		?Nairobi hospital Tel: 0722204114\n		?Nairobi Women’s hospital (Hurlighum) Tel: +254 202726821\n		?Texas cancer centre Tel: +254753623971, +254 202623605\n		?Tenwek mission hospital (Bomet) Tel: +254 202045542, +254 728091900		"));
		ailementdata.add(new AilementData("Causes and control", "?Tobacco i.e. stop smoking or even being close to second hand smoke.\n		?Overweight i.e. reduce your cancer risk by checking on your weight, obesity can lead to cancer\n		?Fruits and vegetables i.e. avoid taking supplements to get the nutrients you need, take a lot of fruits and vegetables\n		?Cut down or avoid alcohol intake\n		?Occupation i.e. embrace safety measures at work places\n		?Infections i.e. cervical cancer and HPV check safety and control measures\n		?Red and processed meat i.e. red is any fresh, minced or frozen beef, pork, lamb or vela. Processed meat (bacon, ham and sausages) small amount of these meats won’t have huge effect on cancer risk\n		?Get more involved in physical activity i.e. be active\n		?Reduce salt intake i.e. high levels of salt intake can increase risk of stomach cancer\n		?Note: other factors like the common bacterial pylori and smoking also play a key role\nAdvice: Seek medical advice from your doctor immediately		"));
		ailementdata.add(new AilementData("3. MALARIA INFORMATION AND MANAGEMENT", "Malaria is a dangerous disease caused by parasite that is transmitted to people through the bites of an infected mosquito. \nMalaria is caused by plasmodium parasites, the parasites are spread to people through the bites of anopheles mosquitoes.\n They bite mainly between dusk and dawn Species of plasmodium that causes malaria in humans are:-\n		Plasmodium falciparium, plasmodium vivax, plasmodium malariae, plasmodium ovale\n		 Specific population, risk groups include:\n		 Young children in stable transmission areas get to develop protective immunity\n		 People with HIV/AIDS\n		 Immigrants from non-endemic areas with their children \n		 Pregnant women i.e. it can lead to maternal death,\n		 International travelers from non- endemic areas i.e. they lack malarial immunity"));
		ailementdata.add(new AilementData("?Symptoms/signs", "?Sweats and chills\n		?Headaches \n		?Musce pains\n		?Diarrhea\n		?High temperature (fever)\n		?Vomiting\nSymptoms appear between 7 – 18 days after becoming infected, but in some cases the symptoms may not appear for up to a year or occasionally even longer An easy way to remember is the ABCD malarial prevention approach as:-\nAwareness risk find out whether you are at risk or getting malaria before traveling\n		Bite prevention – use mosquito repellants and sleep inside a mosquito treated net, cover your skin.\n		Confirm if you are supposed to take malaria prevention tablets, make sure you take the right ant malarial tablets at the right tablet and finish the course\n		Diagnostic test – seek medical assistance if you develop malarial symptoms\n		 Remember to speak to your GP if you are planning to visit an area where there is malarial risk\n		 Medication on malaria and length of treatment will depend on:-\n		Type of malaria, severity of your symptoms, where you caught malaria, taken any ant malarial drugs whether you are pregnant, age. \n		 Complication related to malaria \n		 Serve anaemia – red blood cells are unable to carry enough oxygen around the body leads to weakness\n		 Celebral malaria – happens in rare cases, small blood vessels leading to the brain get blocked, causing seizures, brain damage and eventually coma\n		 Malaria is severe in pregnant women, young children, elderly and babies		"));
		ailementdata.add(new AilementData("Malaria drugs", "Art mother i.e. A Teem, AB safer \n		 AB – ther, Alpharid, Alfadin, Alfamal (treating vesistant falciparium malaria including celebral malaria\n		 Aert sunate i.e. aarnet (50mg), arnet plus, Aba AT, Aba At, Acresunate, afalsi, anti malarial agent\n		Bulaguine\n		 Prescribed for malarial fever i.e. aablaquin\n		 Chloroquine i.e. amoquin, arquin, antima, bitaquine, C- quin, Apa quine (trade names)\n		 Most common atni malarial drugs are:- Quinine sulfate, mefloquine, atoraquone and proguanil, hydroxylchloroquine (plaquinil)\n		 Diagnosing and testing for malaria, some blood tests can take day’s while others can take less than 15 minutes"));
		ailementdata.add(new AilementData("?ASTHMA INFORMATION AND MANAGEMENT", "It causes airways of the lungs to swell, narrow, leading to wheezing, shortness of breath, chest tightness and coughing"));
		ailementdata.add(new AilementData("?Symptoms", "?Coughing especially at night\n		?Shortness of breath\n		?Chest tightness, pain or pressure\n		?Wheezing\n		?Signs of cold or allergies (sneezing, runny nose, nasal congestion, sore throat and headache)\n		?Trouble sleeping\n		?Feeling very tired or week when exercising\n		?Pale, sweaty face\n		?Blue lips/fingernails		"));
		ailementdata.add(new AilementData("•Asthma tests", "Chest x-rays\n		 Lung function tests\n		 Allergy testing,\n arterial blood gas\n		 Spirometry test\n		 Peak flow test"));
		ailementdata.add(new AilementData("•Asthma triggers", "The triggers are different from person to person They are as follows:-\n		Airborne allergies i.e. pollen, cockroaches and dust mites\n		 Respiratory infections i.e. common cold\n		 Physical activity (exercise inducted asthma)\n		 Cold air\n		 Air pollutants and irritants i.e. smoke\n		 Certain medications i.e. aspirin, naproxen, beta blockers\n		 Stress and strong emotions\n		 Sulfites and some preservations added to some type of foods and beverages"));
		ailementdata.add(new AilementData("•Risk factors of asthma", "Overweight, smoking or exposure to second hand smoke, having another allergic conditions, having a mother who smoked while pregnant, exhaust fumes or pollution, occupational triggers"));
		ailementdata.add(new AilementData("•Your treatment and drugs", "Involves recognizing your triggers, taking steps to avoid them and checking your breathing to make sure your daily asthma medications are keeping symptoms under control"));
		ailementdata.add(new AilementData("•Control medications", "Inhaled corticosteroids i.e. flovent HFA, budesonide, flunisolide, mometasone (asmanex) this drugs are generally safe and good for long term use\n		 Leucotriene, modifiers i.e. oral medications (accolade, zileuton, montelukast drugs)\n		 Long acting, beta agonists i.e. inhaled medications i.e. salmeterol (severent), formoterel (feradil, perforomist). Please take them in a combination with an inhaled corticosteroid\n		 Theophylline i.e. it’s a pill that helps keep the airway open (bronchodilator) i.e. theo -24, flexophyllin, its not often used now as in the past years\n		 Quick relief medications:-\n		Short acting beta agonists i.e. preair HFA, ventolin HFA, xopenex, maxair\n		 Atrovent\n		 Oral and intravenous corticosteroids i.e. prednisone and methylprednisolone \n		 Allergy medication i.e. \n		 Include oral and nasal spray antihistamines and decongestants as well as corticosteroid and cromolyn nasal sprays"));
		ailementdata.add(new AilementData("Your asthma action plan", "Work closely with your doctor to create an asthma action plan, writing down when to take certain medications or when to increase or decrease the dose of your medications a list of your triggers and steps you need to take to avoid them		 Your lifestyle and reading available solutions\n		 Avoid your triggers as:- Use of your air conditioner\n		 Decontaminate your décor as pillows, mattresses, box springs\n		 Maintain optimal humidity\n		 Prevent mold spores\n		 Prevent pet dander i.e. avoid pets with fur or feathers, have them regularly groomed this may reduce the amount of dander in your surrounding environs.\n		 Clean regularly \n		 Cover your nose and mouth if its cold out, wear a face mask\n		 Eat fruits and vegetables\n		 Control heart burn\n		 Maintain healthy weight\n		 Get into physical activity i.e. wear face mask in cold areas or warm the air you breath in\nAdvice: Seek medical advice from your doctor 		"));
		ailementdata.add(new AilementData("•HIGH BLOOD PRESSURE", "Known by many as silent killer\n		 It’s advised to check your blood pressure regularly, if not ask your GP"));
		ailementdata.add(new AilementData("•Who is most at risk", "Overweight individuals\n		 Have relative high blood pressure\n		 Smokers\n		 High salt intake\n		 Lack or little intake of fruits and vegetables in their diet\n		 Less active\n		 Consumption of too much coffee or caffeine based drinks\n		 Excessive alcohol consumption\n		 Above 65 years of age"));
		 ailementdata.add(new AilementData("Prevention and treatment", "		Reduce salt intake, loss weight, exercising regularly, healthy diet, cutting down on caffeine, quit smoking, monitor alcohol consumption		 Beta blockers are a common treatment for hypertension		 Normal blood pressure readings will fall below 120/80, the lower number (diastolic) measures pressure at rest between heartbeats, when the heart refills with blood. People in the range between 120 and 139 and also 80 to 89 (for diastolic pressure) have a higher risk of developing heart disease than those with lower readings		 If you have high blood pressure if readings fall average of 140/90 or higher, either number may not have symptoms. At 180/110 and higher, you may be having a hypertensive crisis, take a rest for a few minutes and take your blood pressure again\n\nAdvice: Seek medical help immediately 		"));
		 ailementdata.add(new AilementData("•CARDIOVASCULAR DISEASE", "Describes the disease of the heart or blood vessels\n		 Blood flow to the heart, brain and body can be reduced by blood clot or by buildup of fatty deposits inside an artery that cause the artery to harden and narrow (artherosclerosis)"));
		 ailementdata.add(new AilementData("•Types of cardiovascular are", "Coronary heart disease – Caused by narrowing of your arteries by buildup of fatty material or when oxygen rich blood to your heart is blocked. Coronary arteries are major blood vessels that supply the heart with blood. As the blood vessels narrow because of the buildup of fatty material, blood supply to your heart will be restricted if a coronary artery becomes completely blocked it can cause a heart attack		 \nStroke – It occurs when supply of blood to part of the brain is cut off. This is a serious medical condition. If blood supply to blocked, brain cells will begin to die, this can cause brain damage and probably death"));
		 ailementdata.add(new AilementData("•Symptoms/signs of stroke", "		Face or mouth or eye may have drooped one side, the person maybe unable to smile and talk\n		 Unable to lift their arms and keep it raised because of weaknesses \n		 Please consult a doctor immediately or call an ambulance for medical help\n		 Peripheral arterial disease\n		 Occurs when there’s blockage in the arteries to your limbs (usually legs)		"));		 ailementdata.add(new AilementData("•Symptoms/signs", "		Pain in your legs while walking\n		 Pain also in both of your thighs, hips or calves and experiencing some heaviness in your legs muscle.\n This symptoms usually comes and goes		"));
		 ailementdata.add(new AilementData("•Aortic disease", "		Aortic is the largest blood vessel in your body walls or the aorta becomes weakened and bulges outwards. You will experience pain in your chest, back or abdomen 		"));
		 ailementdata.add(new AilementData("•Your risks for cardiovascular disease", "•Your risks for cardiovascular disease\n		High blood pressure\n		 Smoking\n		 High blood cholesterol\n		 Diabetes\n		 Lack of exercise i.e. exercise atleast 30 minutes a day\n		 Being overweight or obese\n		 Family history on the disease\n		 The amount of alcohol you drink and how you deal with stress are also thought to be linked to the risk of developing cardiovascular disease		"));
		 
		 ailementdata.add(new AilementData("Cardiovascular disease in children", "		Bad eating habits are attributed to this as:-\n		Fat in your child’s diet\n		 Salt in your child’s diet\n		 Sugar in your child’s diet\n		 Physical activity of your child\n		 When to seek medical advice\n		 Chest pain\n		 Shortness of breath\n		 Fainting \n		 It’s easier to treat especially when detected early		"));
		 ailementdata.add(new AilementData("What causes heart infection?", "Such as pericarditis, endocarditis, myocarditis, caused when a bacterium virus or chemical reaches your heart muscle		 Most common of heart infections are:-\n		Bacteria, viruses and parasites \n		 Complications of the cardiovascular disease?\n		 Heart failure, heart attack, stroke, aneurysm, peripheral artery disease, sudden cardiac arrest\n		 Advice:- Seek medical emergency\n		 Your tests and diagnosis\n		 This may depend according to what your doctor thinks you may have\n		 Blood test\n		 X-ray tests i.e. chest\n		 Electrocardiogram (ECG) i.e. records electrical signals and help tell your doctor irregularities in heart rhythm and structure\n		 Holter monitoring i.e. records heart rhythm irregularities that are not found during an ECG\n		 Echocardiogram i.e. includes an ultrasound of your chest and shows your heart’s function and structure\n		 Cardiac catheterization\n		 Cardiac computerized tomography (CT) scan\n		 Cardiac magnetic resonance Imaging (MRI)"));
		 ailementdata.add(new AilementData("Treatments", "		Lifestyle changes\n		 Medications\n		 Medical procedures or surgery		"));
		 ailementdata.add(new AilementData("DENTAL HEALTH INFORMATION AND MANAGEMENT", "Dentistry world health organization defines it as science and art of preventing, diagnosing and treating diseases, injuries and malformations of the teeth, jaws and mouth		 Dentists are required to put the welfare of the patients before any other consideration"));
		 ailementdata.add(new AilementData("Your oral hygiene", "Processes used for removal of dental microbial plaque from your teeth and maintaining a healthy mouth environment, it prevents problems affecting teeth, gums or other tissues of the oral cavity\nYour oral hygiene methods \nTooth brushing – Keeps away bacteria and food particles, it also has a toothpaste helps in clearing microbial agents and strengthen teeth		 \nTeeth flossing – Clears areas between the teeth and under the gum line where the tooth brush bristles can’t reach\n		 Mouth washing – If mouth muses can be used as a complementary to brushing and flossing keep your toothbrush 6 feet away from the toilet since when you flush the toilet there are airborne bacteria"));
		 ailementdata.add(new AilementData("Your basic oral hygiene tips", "		Brush your teeth atleast twice a day and for atleast 2 minutes every tooth brushing sessions\n		 Use toothpastes and mouthwashes that contain fluoride\n		 Use dental floss\n		 Use interdentally cleaning tools i.e. bridges, braces or implants\n		 Avoid sugary and acidic foods i.e. avoid too sugary drinks and foods\n		 Visit your dentist for professional teeth cleaning every 6 months\n		 Good oral hygiene is essential and it should be combined with proper healthy diet and regular dental visits "));
		 ailementdata.add(new AilementData("•Dental health conditions affecting human mouth and teeth For children are", "•Fluorosis\n		•Teething\n		•Thumb sucking\n		•Baby bottle tooth decay\n		•Adults are:-\n		•Tongue syndrome\n 		•Halitosis (bad breath)\n		•Teeth grinding/clenching\n		•Cancer sores\n		•Dental plaque\n		•Dry mouth\n		•Mouth cancer\n	•Oral leokoplalcia\n		•Toothaches\n		•Tooth decay\n		•Tooth erosion\n		•Tooth injuries\n		•Tooth discoloration\n		•Periodontal diseases\n		•Sensitive teeth\n		•Tooth abscess		"));
		 ailementdata.add(new AilementData("Roles of a dentist", "Evaluation and professional advice on monitoring and prevention\n		 Dental restorations (fillings, crowns)\n Orthodontics (braces)\n	 		 Prosthetics (dentures, implants) \n		 Endodontic (root canal)\n		 Periodontal therapy (gum treatment)\n		 Tooth extractions\n		 Cosmetic treatments i.e. teeth whitening and realignment\n		 Administer medications i.e. antibiotics, fluorides, sedatives, local anesthetics and other medications"));
		 ailementdata.add(new AilementData("Cosmetic dentistry", "Demand for cosmetic dentists has been continuously increasing worldwide as more and more individuals than ever before are looking to improve their facial appearance.		 Most people prefer their teeth to be straighter and whiter, giving us a beautiful smile. Un attractive smile can be at times a negative effects on an individual’s self esteem, confidence. Cosmetic dentistry helps hide signs of aging on our teeth\n		 Cosmetic dentistry solutions\n		Fix the problem of stained and discolored teeth\n		 Fix the problem of gaps between teeth\n		 Fix the problem of uneven teeth \n		 Fix the problem of creaked or crowded teeth\n		 Fix the problem of broken or chipped teeth\n		 Fix the problem of gummy smile\n		 Fix the problem of missing teeth\n		 Please note many of the procedures may be part of a smile makeover could be performed by other dentists, it is important that the treatment plan be prepared by cosmetic dentist. Babies should start seeing dentist by their first birthday or immediately first tooth comes in.\n\nAdvice:- For further information consult your dentist"));
		 ailementdata.add(new AilementData("DERMATOLOGY MANAGEMENT AND INFORMATION", "		It’s a science that deals with hair, nails, skin and their related diseases 		"));
		 ailementdata.add(new AilementData("SKIN DISEASES", "Classified as:-\n		Bacterial, fungal, viral and animal induced (insects, mites and worms)		"));
		 ailementdata.add(new AilementData("Areas of attack (sites of body)", "•Hair, scalp, nail\n		•Skin folds\n		•Genitals\n		•Feet\n		•Mouth\n		•Ear\n		•Face		"));
		 ailementdata.add(new AilementData("Diseases related to this are:-", "•Lesions, cancer and tumors\n		•Acne\n•Dermatitis, allergies\n		•Systemic diseases\n		•Blisters\n		•Immunological disorders\n		•Scaly skins diseases\n		•Ulcers/erosion\n		•Pigmentation problems\n		•Deep skin disorders\n		•Itching\n		•Vascular skin problem		"));
		 ailementdata.add(new AilementData("Treatment and procedures", "•Use of creams\n		•Oral therapy (drugs)\n		•Cosmetic treatments\n		•Tests and ultraviolet therapy\n		•Skin surgery\n		•Injections\n\nAdvice:- Seek specialized medical advice		"));
		 
		 ailementdata.add(new AilementData("•OPTOMETRIC INFORMATION AND MANAGEMENT", "Eyes are the most valuable senses you have they provide nearly 100% of information you take in		 Bad vision can cause your eyes muscles to work overtime leading to tired eyes, headache and dry eyes. Constant exposure to air conditioner at work place can cause dry eyes. It’s recommended to do an eye exam atleast every year unless your, optometrist tells you otherwise		 Take a balanced diet for your visual health"));
		 ailementdata.add(new AilementData("Your eye defects", "•Astigmatism\n		•Long sightedness\n		•Short sightedness\n		•Your eye disease\n		•Dry eyes – Affects computer user and post-menopausal women, use artificial eye drops for solving that\n		•Cataracts – Blurred or distorted vision\n		•Conjunctivitis – Occur by bacterial, virus, allergic or chemicals infections\n		•Glaucoma – Untreated can cause vision loss or tuned vision that can lead to blindness. Please consult for medical help immediately. Do regular eye checks		"));
		 ailementdata.add(new AilementData("Computer vision related problems are;-", "This problems comes on long term exposure on computer at a shorter focusing distances"));
		 ailementdata.add(new AilementData("Signs of computer vision related problems ", "Physical stress\n		 Fatigue\n Teary eyes\n		 Eyestrain associated to discomfort in areas around your neck and shoulders\n		 Prevention \n		 Use UV screen filter on computers\n		 Proper occupational health i.e. keyboards, screens and chairs\n		 Correct prescription eye wear\n		 Regular breaks from close work are also required\n		 A general eye exam takes 45 minutes. Sunglasses protects UV radiation, exposure to this rays contribute to early wrinkling, cataracts, sunburn of eye and eyelid and other forms of skin cancer.\n		 Sunglasses can provide eye protection when playing sports"));
		 ailementdata.add(new AilementData("Your child’s eyesight", "Children learn mostly by seeing children’s rarely complain, they often adjust to see things clearly. It is vital as a parent to monitor your child closely for this signs as follows:-\n		Bumping into things\n		 Below performance in respect to their potential \n		 Frequent headaches \n		 Frequent rubbing of their eyes\n		 Turns or tilts their head so that they can use one eye\n		 Losing their position on a page\n		 When reading they use their finger to maintain his/her position while reading \n		 Holding reading material very close\n\n\nConsult your optometrist for further medical advice"));

		 
		 dialog.dismiss();
					ShowNext(null);
		
	}
	public void ShowNext(View view){
		
		if (AmAtpage<ailementdata.size()-1) {
			
			AmAtpage++;
			
			((TextView)findViewById(R.id.pageat)).setText(( AmAtpage+1) +"of" +ailementdata.size());
			
			((TextView)findViewById(R.id.header)).setText(ailementdata.get(AmAtpage).getHeader());
			((TextView)findViewById(R.id.description)).setText(ailementdata.get(AmAtpage).getDescription());
			
			
		}
		else {
			Toast.makeText(getApplicationContext(), "This is the last page", Toast.LENGTH_LONG).show();
		}
	}
	public void ShoePrevious (View view){
		if (AmAtpage>0) {
			AmAtpage--;

			((TextView)findViewById(R.id.pageat)).setText(( AmAtpage+1) + " of " +ailementdata.size());
			
			((TextView)findViewById(R.id.header)).setText(ailementdata.get(AmAtpage).getHeader());
			((TextView)findViewById(R.id.description)).setText(ailementdata.get(AmAtpage).getDescription());
			
		}
		else {
			Toast.makeText(getApplicationContext(), "This is the First page", Toast.LENGTH_LONG).show();
		}
	}
	public void Share(View view){
		Intent intent = new Intent(Intent.ACTION_SEND);
		intent.setType("text/plain");
		intent.setPackage("com.whatsapp");
		intent.putExtra(Intent.EXTRA_TEXT, ailementdata.get(AmAtpage).getDescription()+"");
		try{
			startActivity(intent);
			}catch (Exception e) {
				// TODO: handle exception
				Toast.makeText(this, "Hey download whatsapp", Toast.LENGTH_LONG).show();
			}
}
}